### ISSUE TITLE
Runtime error when using Assert.Fail()

### ISSUE THREAD

**Issue by sam-mckay** [game-ci/documentation#175]
**Bug description**
The sample workflow at the bottom of this page (https://game.ci/docs/github/test-runner) fails if you have unit tests that fail 

This is possible intentional but it's very unclear from the logs and docs (https://game.ci/docs/github/test-runner) 

Error from the workflow run: Error: Cannot read property 'split' of undefined

**How to reproduce**

1. Add workflow from bottom of here (https://game.ci/docs/github/test-runner) to a repo with a unity project
2. Add a failing unit test (Assert.Fail)
3. Create PR to run workflow

- **Expected behavior**

I expected the workflow to complete successfully but mark it as failed due to failing tests, instead of erroring halfway through

**Additional details**

You can view my run here plus source code
https://github.com/sam-mckay/Unity-Github-Actions-Testing/runs/2646433423

**Comment by webbertakken** [comment]
> Error: Cannot read property 'split' of undefined

This is a runtime error, not a failing test. Make sure that you're not testing null pointers as they will resolve before assert is called (as it is an argument to the assert function).

**Comment by sam-mckay** [comment]
> > Error: Cannot read property 'split' of undefined
> 
> This is a runtime error, not a failing test. Make sure that you're not testing null pointers as they will resolve before assert is called (as it is an argument to the assert function).

I'm not sure that's correct, 

See below commit and test status history 
![image](https://user-images.githubusercontent.com/9663483/119235295-b20a3a00-bb29-11eb-91b7-863e499d4dc5.png)

and the content of the commit that made the workflow pass

![image](https://user-images.githubusercontent.com/9663483/119235315-c6e6cd80-bb29-11eb-81fa-7d2bae892ea6.png)

Assert.Fail() shouldn't cause this workflow step to error

**Comment by webbertakken** [comment]
Are you saying you want your test step to pass when the tests are failing?

The convention in CI is for a job to fail if something goes wrong. That way it will stop you from merging into your main branch.

**Comment by sam-mckay** [comment]
Not at all,

I'm saying it seems wrong that the workflow suffers a fatal error when a test is failing rather than reporting that the status check result is failed 

Naturally it shouldn't pass if the test fails, but letting a fatal error be the cause of why it is marked failing is both confusing and unconventional.

Imagine a case where there is additional logic to perform after this step like posting results, the fatal error may prevent that surely?

**Comment by webbertakken** [comment]
Agreed. But then I've not seen this happen before myself (hence my first comment).

Thanks for reporting this bug.

**Comment by webbertakken** [comment]
For reference, this is what a failure normally looks like

![image](https://user-images.githubusercontent.com/20756439/119237381-ca378480-bb3c-11eb-94fa-88ce0dd6dd00.png)

**Comment by sam-mckay** [comment]
Yeah that's much more like what I was expecting, hence reporting this, I assumed I'd done something wrong until I tested the sample scripts in the docs and then out of sheer curiosity fixed my intentionally failing test (so I could see the functionality of this action). 

No worries, I have a 100% repro on my repository linked at the top so feel free to fork for testing any fixes

**Comment by webbertakken** [comment]
Does it show the same behaviour for `Assert.IsTrue(false);`?

**Comment by webbertakken** [comment]
The error happens in the results parser on `src/model/results-check.js:104`

**Comment by webbertakken** [comment]
cc: @davidmfinol as you wrote this, maybe you know what could be wrong there?

**Comment by sam-mckay** [comment]
> Does it show the same behaviour for `Assert.IsTrue(false);`?

I've not tested that but I can try later

**Comment by davidmfinol** [comment]
Looks like `Assert.Fail()` causes [annotation.message](https://github.com/game-ci/unity-test-runner/blob/main/src/views/results-check-details.hbs#L10) to be [undefined](https://github.com/sam-mckay/Unity-Github-Actions-Testing/runs/2646433423#step:4:3840).
I believe https://github.com/game-ci/unity-test-runner/pull/125 should fix it.

**Comment by davidmfinol** [comment]
We merged the fix to main.
@sam-mckay can you confirm if `uses: game-ci/unity-test-runner@main` works for you now?

**Comment by sam-mckay** [comment]
This seems to have fixed the error I was seeing previously, although it was just replaced it with another error instead
![image](https://user-images.githubusercontent.com/9663483/120069265-e0819b00-c07c-11eb-98b0-75a232bce472.png)

So Assert.Fail still doesn't fail in the same way as other test failures appear to here: https://github.com/game-ci/documentation/issues/175#issuecomment-846447028

**Comment by davidmfinol** [comment]
Yep, looks like we just moved the problem further down.
I added another check with https://github.com/game-ci/unity-test-runner/pull/128

This time, I ran a before test (with the same result you got): https://github.com/finol-digital/Card-Game-Simulator/actions/runs/891231636
And an after test (with it finally fixed): https://github.com/finol-digital/Card-Game-Simulator/actions/runs/891247760

I've merged this fix to main as well, so closing this issue.
Please re-open if you still see the issue in the main branch.
